# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb18ce2a7a7201612f6a28f6ac064c372523731df4c8e112d47d01de8f39f54de393053a22d9af8a2d0649f99fed0f9eb50dd1b828ef11b0c38640e4551a787d

test:
  secret_key_base: 0996f595d09fa57c12acadaa9f10655ea9216a28505bb25a2c492ce40c2e2d4cbcddb0172ea06b7a37207d088193103c0cb3f32414445f3becf3df64bad0fff2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
